[book]
authors = ["Brett Chalupa", "Dragon Rider Community"]
language = "en"
src = "src"
title = "Building Games with DragonRuby"
description = "A beginner-friendly guide to programming 2D games with DragonRuby Game Toolkit."

[output.html]
git-repository-url = "https://github.com/DragonRidersUnite/book"

[output.html.print]
enable = false
